name : Update Live Governance Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
permissions:
  contents: write
jobs:
  update-live-governance-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y jq curl
      - name: Run governance actions update script
        run: |
          echo "Running governance actions update script..."
          bash script/live-ga.sh
      - name: Set up Git user
        run: |
          git config --global user.email "ebardho17@epoka.edu.al"
          git config --global user.name "Elena Bardho"
      - name: Commit and push changes
        run: |
          echo "Committing and pushing changes..."
          NEW_FILES="live-ga.json"
          git add -f $NEW_FILES
          git commit -m "Update governance actions data"
          git push origin $(git rev-parse --abbrev-ref HEAD)
